using System.ComponentModel;

namespace ProfanityEdit.Models
{
    public enum GenerateMethodEnum
    {
        [Description("Autogenerated Profanity Edit")]
        AutogeneratedProfanityEdit,

        [Description("Verified Profanity Edit")]
        VerifiedProfanityEdit,

        [Description("Custom Edit")]
        CustomEdit
    }
}